In [1]:
import numpy as np
import sys

sys.path.append("../")

x_train = np.load("../data/x_train.npy")
y_train = np.load("../data/y_train.npy")
x_test = np.load("../data/x_test.npy")
y_test = np.load("../data/y_test.npy")

print("x_train", x_train.shape)
print("y_train", y_train.shape)
print("x_test", x_test.shape)
print("y_test", y_test.shape)

x_train (60000, 256)
y_train (60000,)
x_test (10000, 256)
y_test (10000,)


In [39]:
data = np.random.randint(0, 10, size=(6, 5))
data

array([[2, 6, 3, 8, 2],
       [4, 2, 6, 4, 8],
       [6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1],
       [3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1]])

In [42]:
label = np.random.randint(0, 3, size=(data.shape[0]))
label

array([2, 1, 1, 1, 1, 1])

In [43]:
index = (label == 1)
x = data[index, :]
x

array([[4, 2, 6, 4, 8],
       [6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1],
       [3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1]])

In [3]:
c = np.array([5, 6, 7])
b + c

array([10, 13, 16])

In [7]:
a.sum(axis=0)

array([5, 7, 9])

In [10]:
5 in l

True

In [7]:
a = np.array([0, 0, 1, 1, 0, 1])
a

array([0, 0, 1, 1, 0, 1])

In [8]:
a[np.where(a==0)] = -1
a

array([-1, -1,  1,  1, -1,  1])

In [1]:
import tensorflow as tf

noise = tf.random.normal([256, 100])
noise.shape

TensorShape([256, 100])