In [2]:
import numpy as np
import sys

sys.path.append("../")

x_train = np.load("../data/x_train.npy")
y_train = np.load("../data/y_train.npy")
x_test = np.load("../data/x_test.npy")
y_test = np.load("../data/y_test.npy")

print("x_train", x_train.shape)
print("y_train", y_train.shape)
print("x_test", x_test.shape)
print("y_test", y_test.shape)

x_train (60000, 256)
y_train (60000,)
x_test (10000, 256)
y_test (10000,)


In [3]:
import numpy as np
np.max(noise.numpy())

3.2076325

In [4]:
np.min(noise.numpy())

-2.6061578

In [1]:
from tensorflow.keras.datasets import fashion_mnist
import numpy as np
from collections import Counter
import sys
sys.path.append('../')

import data_loader

#(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
#x_train = x_train / 255.0
x_train, y_train, x_test, y_test = data_loader.load_data()
print(x_train.shape)
print(np.max(x_train))
print(np.min(x_train))
# y_train = train[:,-1].shape
# Counter(y_train)

训练集共有60000个样本
测试集共有10000个样本
训练集共有10个类别
对训练集排序
(60000, 187)
1.0000000000000002
0.0


In [21]:
import tensorflow as tf

n = tf.ones([3, 7])
n

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
n * (1.0 / 7)

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[0.14285715, 0.14285715, 0.14285715, 0.14285715, 0.14285715,
        0.14285715, 0.14285715],
       [0.14285715, 0.14285715, 0.14285715, 0.14285715, 0.14285715,
        0.14285715, 0.14285715],
       [0.14285715, 0.14285715, 0.14285715, 0.14285715, 0.14285715,
        0.14285715, 0.14285715]], dtype=float32)>

In [10]:
5 in l

True

In [7]:
a = np.array([0, 0, 1, 1, 0, 1])
a

array([0, 0, 1, 1, 0, 1])

In [8]:
a[np.where(a==0)] = -1
a

array([-1, -1,  1,  1, -1,  1])

In [1]:
import tensorflow as tf

noise = tf.random.normal([256, 100])
noise.shape

TensorShape([256, 100])