In [1]:
import numpy as np
import sys

sys.path.append("../")

x_train = np.load("../data/x_train.npy")
y_train = np.load("../data/y_train.npy")
x_test = np.load("../data/x_test.npy")
y_test = np.load("../data/y_test.npy")

print("x_train", x_train.shape)
print("y_train", y_train.shape)
print("x_test", x_test.shape)
print("y_test", y_test.shape)

x_train (60000, 256)
y_train (60000,)
x_test (10000, 256)
y_test (10000,)


In [16]:
class Foo():
    def __init__(self, input):
        self.input = input

    def display(self):
        print(self.input)

foo = []
for i in range(3):
    temp = Foo(i)
    foo.append(temp)

foo[2].display()

2


In [21]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 2, 3, 4])
import math
a- b

array([1, 2, 3, 4])

In [2]:
b = a.sum(axis=0)
b

array([5, 7, 9])

In [3]:
c = np.array([5, 6, 7])
b + c

array([10, 13, 16])

In [7]:
a.sum(axis=0)

array([5, 7, 9])

In [10]:
5 in l

True

In [7]:
a = np.array([0, 0, 1, 1, 0, 1])
a

array([0, 0, 1, 1, 0, 1])

In [8]:
a[np.where(a==0)] = -1
a

array([-1, -1,  1,  1, -1,  1])

In [1]:
import tensorflow as tf

noise = tf.random.normal([256, 100])
noise.shape

TensorShape([256, 100])