In [18]:
import numpy as np

a = np.random.randint(1, 5, size=(1, 3))
b = np.random.randint(6, 10, size=(2, 3))
c = np.concatenate((a, b), axis=0)
c

array([[4, 3, 4],
       [6, 7, 9],
       [9, 9, 7]])

In [26]:
a = np.array([1, 2, 3])
b = a.reshape((1, -1))

In [27]:
b.shape

(1, 3)

In [31]:
for i in range(5):
    for j in range(3):
        if j==2:
            break
    print(i, j)

0 2
1 2
2 2
3 2
4 2


In [10]:
b = np.random.multivariate_normal(data.mean(axis=0), np.cov(data.T), size=10)

In [11]:
b.mean(axis=0)

array([5.64809471, 6.36728367, 6.01419095, 2.48650734, 3.47537924,
       6.3833747 ])

In [7]:
a.sum(axis=0)

array([5, 7, 9])

In [10]:
5 in l

True

In [7]:
a = np.array([0, 0, 1, 1, 0, 1])
a

array([0, 0, 1, 1, 0, 1])

In [8]:
a[np.where(a==0)] = -1
a

array([-1, -1,  1,  1, -1,  1])

In [1]:
import tensorflow as tf

noise = tf.random.normal([256, 100])
noise.shape

TensorShape([256, 100])