In [15]:
import tensorflow as tf
from tensorflow.keras.models import load_model

clf = load_model("../models/classifier")
noise = tf.random.normal([1, 256])

In [16]:
clf(noise)

<tf.Tensor: shape=(1, 7), dtype=float32, numpy=
array([[0.01039513, 0.0044502 , 0.16681345, 0.1567052 , 0.179199  ,
        0.00286978, 0.47956726]], dtype=float32)>

In [12]:
from tensorflow.keras.datasets import fashion_mnist
import numpy as np
from collections import Counter

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train.reshape(x_train.shape[0], -1)
train = np.c_[x_train, y_train]

train = train[np.argsort(train[:,-1]), :]
print(train)
# y_train = train[:,-1].shape
# Counter(y_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 9]
 [0 0 0 ... 5 0 9]
 [0 0 0 ... 0 0 9]]


In [21]:
import tensorflow as tf

n = tf.ones([3, 7])
n

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
n * (1.0 / 7)

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[0.14285715, 0.14285715, 0.14285715, 0.14285715, 0.14285715,
        0.14285715, 0.14285715],
       [0.14285715, 0.14285715, 0.14285715, 0.14285715, 0.14285715,
        0.14285715, 0.14285715],
       [0.14285715, 0.14285715, 0.14285715, 0.14285715, 0.14285715,
        0.14285715, 0.14285715]], dtype=float32)>

In [10]:
5 in l

True

In [7]:
a = np.array([0, 0, 1, 1, 0, 1])
a

array([0, 0, 1, 1, 0, 1])

In [8]:
a[np.where(a==0)] = -1
a

array([-1, -1,  1,  1, -1,  1])

In [1]:
import tensorflow as tf

noise = tf.random.normal([256, 100])
noise.shape

TensorShape([256, 100])