In [1]:
from tensorflow.keras.datasets import fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [2]:
import numpy as np

np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [3]:
x_train_ = x_train.reshape(x_train.shape[0], -1)
x_train_.shape

(60000, 784)

In [5]:
x_train_.shape[1]

784

In [20]:
l = np.array([0, 1, 2, 3, 4, 5, 6])
label = np.array([5, 6, 7, 8, 9])
#label = int(l.__contains__(label))
label[label <= 6] = 1
label[label > 6] = -1

label

array([ 1,  1, -1, -1, -1])

In [10]:
5 in l

True

In [7]:
a = np.array([0, 0, 1, 1, 0, 1])
a

array([0, 0, 1, 1, 0, 1])

In [8]:
a[np.where(a==0)] = -1
a

array([-1, -1,  1,  1, -1,  1])